version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongo-nginx
    restart: always
    volumes:
      - ./mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASS
      MONGO_INITDB_DATABASE: $MONGO_DB

  backend:
    build: ./backend
    container_name: backend-nginx
    restart: always

    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://$MONGO_USER:$MONGO_PASS@$MONGO_HOST:27017/$MONGO_DB?authSource=admin

  frontend:
    build: 
      context: ./frontend
      args:
        REACT_APP_BACKEND_URI: http://todo.local/api/
    container_name: frontend-nginx
    restart: always
    depends_on:
      - backend

  nginx:
    build: ./nginx
    container_name: nginx
    depends_on:
      - backend
      - frontend
    ports:
      - 80:80
      - 443:443